Add a getNode() function for class CocosNode.
It is to fix the building error introduced by ae4bcdea5eafba5ff4c780b8ab512ba25dec57ce:
  DragonBones/Cocos2dxDisplayBridge.cpp:13:27: error: 'class dragonBones::CocosNode' has no member named 'getNode'.